# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'level_choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(250, 144)
        Form.setMinimumSize(QtCore.QSize(250, 144))
        Form.setMaximumSize(QtCore.QSize(250, 144))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 241, 92))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font-size: 15px; font-weight: bold")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.easy = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.easy.setObjectName("easy")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.easy)
        self.verticalLayout.addWidget(self.easy)
        self.medium = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.medium.setChecked(True)
        self.medium.setObjectName("medium")
        self.buttonGroup.addButton(self.medium)
        self.verticalLayout.addWidget(self.medium)
        self.hard = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.hard.setObjectName("hard")
        self.buttonGroup.addButton(self.hard)
        self.verticalLayout.addWidget(self.hard)
        self.ok_button = QtWidgets.QPushButton(Form)
        self.ok_button.setGeometry(QtCore.QRect(0, 110, 241, 23))
        self.ok_button.setObjectName("ok_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Выбор уровня"))
        self.label.setText(_translate("Form", "Выберите уровень сложности:"))
        self.easy.setText(_translate("Form", "Простой"))
        self.medium.setText(_translate("Form", "Средний"))
        self.hard.setText(_translate("Form", "Сложный"))
        self.ok_button.setText(_translate("Form", "OK"))
